const WORK_EXPERIENCE = [
  {
    type: 'work',
    company: 'Amazon Web Services',
    companyUrl: 'https://aws.amazon.com/',
    description: [
      'Maintained and built new features for several applications that power AWS Activate such as the AWS Activate Console and Activate Admin CMS',
      'Architected and implemented Tech Hub, a place where startups get real-time updates on the health of their AWS environment, explore AWS services, and connect with AWS Support',
      'Improved code quality by writing front-end unit and integration tests for components with no test coverage and improved existing tests',
      'Integrated a Slack bot using AWS Chatbot and AWS SNS to notify engineers of critical events related to our operations',
      'Worked with product managers and UX designers to test and push new ideas using experimentation methods such as A/B tests',
    ],
    endDate: {
      displayDate: 'Present',
    },
    jobTitle: 'Front End Engineer',
    startDate: {
      displayDate: 'Jul 2020',
      valueDate: '2020-07',
    },
    technologies: [
      'JavaScript',
      'React',
      'CSS',
      'HTML',
      'TypeScript',
      'AWS',
      'AWS CloudWatch',
      'AWS S3',
      'AWS CloudFront',
      'AWS DynamoDB',
      'AWS ChatBot',
      'AWS SNS',
      'AWS Lambda',
      'AWS Activate for Startups',
      'Git',
      'Agile',
    ],
  },
  {
    type: 'work',
    company: 'Cox Automotive',
    companyUrl: 'https://www.coxautoinc.com',
    description: [
      'Built and maintained several microservices, web applications, and the internal component library for the consumer-facing website KBB.com using React, TypeScript, GraphQL, Apollo Server, Apollo Client, Node.js, .NET, Terraform, and AWS',
      'Architected and built a scheduled data process that pulls data from multiple internal and external APIs in parallel and aggregates them for consumption by various teams',
      'Maintained and added new functionality to internal SDKs responsible for core functionality such as data layer, ads, and SEO metadata',
      'Member of an internal web performance committee that focused on maintaining high-performing applications and monitoring metrics',
      'Speaker at talks on various topics including but not limited to How to Become an AWS Certified Developer Associate, Web Performance, AWS Amplify, and AWS AppSync',
    ],
    endDate: {
      displayDate: 'Jul 2020',
      valueDate: '2020-07',
    },
    jobTitle: 'UI Engineer',
    startDate: {
      displayDate: 'May 2017',
      valueDate: '2017-05',
    },
    technologies: [
      'JavaScript',
      'React',
      'GraphQL',
      'Apollo',
      'AWS',
      'AWS CloudWatch',
      'AWS S3',
      'AWS CloudFront',
      'AWS DynamoDB',
      'AWS Lambda',
      'CSS',
      'HTML',
      'TypeScript',
      'Node.js',
      'Terraform',
      'Jest',
      'New Relic',
      'Storybook',
      'Emotion',
      'styled-components',
      'Splunk',
      'webpack',
      'Git',
      'Agile',
    ],
  },
  {
    type: 'work',
    company: 'SalesPad',
    companyUrl: 'https://www.salespad.com/',
    description: [
      'Internship completed during the spring and summer of my junior year',
      'Worked on package builder solution that packaged ​n​ sized items into ​k​ sized boxes (related to the Bin packing problem)',
      'Collaborated with developers, managers, and product team to learn about product and development lifecycles and built out small features',
      'Analyzed performance, maintained, and enhanced the SalesPad application',
    ],
    endDate: {
      displayDate: 'Aug 2015',
      valueDate: '2015-08',
    },
    jobTitle: 'Junior C# Developer',
    startDate: {
      displayDate: 'Mar 2015',
      valueDate: '2015-05',
    },
    technologies: ['C#', 'Git', 'Jira', 'Agile'],
  },
  {
    type: 'education',
    company: 'Calvin University',
    companyUrl: 'https://calvin.edu/',
    description: [
      'Graduated in 2016 with a Bachelor of Science (B.S.), Computer Science',
      'Completed courses like Computer Security, Data Structures and Algorithms, High Performance Computing, Operating Systems and Networking, Programming Language Concepts, Software Engineering, Website Administration, and Agile Game Development in South Korea',
    ],
    endDate: {
      displayDate: 'June 2016',
      valueDate: '2016-06',
    },
    jobTitle: 'CS Undergrad Student',
    startDate: {
      displayDate: 'Sep 2013',
      valueDate: '2013-09',
    },
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'C#',
      'C++',
      'C',
      'Java',
      'Python',
      'LISP',
      'Ruby',
      'MeteorJS',
      'AngularJS',
      'Objective-C',
      'Drupal',
      'Assembly',
      'Unity',
      'Git',
    ],
  },
];

export default WORK_EXPERIENCE;
