import A from '../components/svg/A';
import C from '../components/svg/C';
import S from '../components/svg/S';

const WORK_EXPERIENCE = [
  {
    company: 'Amazon Web Services',
    companyUrl: 'https://aws.amazon.com/',
    description: [
      'I am currently a Front End Engineer at AWS Activate where I design, develop, and ship user interfaces and experiences for startups of all sizes to build, grow, and scale. I work on several applications that power AWS Activate such as the AWS Activate Console and Activate Admin CMS.',
      'Within two months of joining the team, I led the development of a feature called Tech Hub which was an integral part of the GA Launch of the AWS Activate Console. I designed an alternative solution to an outdated research document that was completed before I joined the team, collaborated with internal and external stakeholders, integrated with several external AWS services and an internal CMS, implemented and tested the feature, and launched it into production.',
      'Improved codebase by writing front-end unit tests and integration tests for components with no test coverage and improved existing tests.',
      'Integrated a Slack bot using AWS Chatbot and AWS Simple Notification Service (SNS) to notify engineers of critical events related to our operations.',
      'Worked with product managers and UX designers to test and push new ideas using experimentation methods such as A/B tests.',
      'Researched and documented region failover solutions for our systems.',
    ],
    endDate: {
      displayDate: 'Present',
    },
    jobTitle: 'Front End Engineer',
    startDate: {
      displayDate: 'Jul 2020',
      valueDate: '2020-07',
    },
    svgComponent: A,
    svgPrimaryColor: '#FF9900',
    svgSecondaryColor: '#E08700',
    technologies: [
      'JavaScript',
      'React',
      'CSS',
      'HTML',
      'TypeScript',
      'AWS',
      'AWS CloudWatch',
      'AWS S3',
      'AWS CloudFront',
      'AWS DynamoDB',
      'AWS ChatBot',
      'AWS SNS',
      'AWS Lambda',
      'AWS Activate for Startups',
      'Git',
      'Agile',
    ],
  },
  {
    company: 'Cox Automotive',
    companyUrl: 'https://www.coxautoinc.com',
    description: [
      'Built and maintained several microservices, web applications, and the internal component library for the consumer-facing website KBB.com using React, TypeScript, GraphQL, Apollo Server, Apollo Client, Node.js, .NET, Terraform, and AWS.',
      'Stretched backend skills by using .NET to architect and build a scheduled data process that pulls data from multiple internal and external APIs in parallel and aggregates them for consumption by various teams.',
      'Built and maintained components for KBB.com’s internal component library using React, Emotion, TypeScript, Jest, and Storybook.',
      'Maintained and added new functionality to internal SDKs responsible for core functionality such as data layer, ads, and SEO metadata.',
      'Member of an internal web performance committee that pushed the engineering organization to focus on maintaining high-performing applications and monitoring metrics by using tools like webpack, New Relic, Splunk, CloudWatch, and Developer Tools and techniques such as lazy loading, code-splitting, and image optimizations.',
      'Speaker at talks given to internal team members on various topics learned from conferences and self-learning including but not limited to How to Become an AWS Certified Developer Associate, Web Performance, AWS Amplify, and AWS AppSync.',
      'Promoted STEM careers and mentored elementary, middle, and high school students at various times of the year through programs like Hour of Code and Junior Achievement USA.',
    ],
    endDate: {
      displayDate: 'Jul 2020',
      valueDate: '2020-07',
    },
    jobTitle: 'UI Engineer',
    startDate: {
      displayDate: 'May 2017',
      valueDate: '2017-05',
    },
    svgComponent: C,
    svgPrimaryColor: '#4072C9',
    svgSecondaryColor: '#315FAF',
    technologies: [
      'JavaScript',
      'React',
      'GraphQL',
      'Apollo',
      'AWS',
      'AWS CloudWatch',
      'AWS S3',
      'AWS CloudFront',
      'AWS DynamoDB',
      'AWS Lambda',
      'CSS',
      'HTML',
      'TypeScript',
      'Node.js',
      'Terraform',
      'Jest',
      'New Relic',
      'Storybook',
      'Emotion',
      'styled-components',
      'Splunk',
      'webpack',
      'Git',
      'Agile',
    ],
  },
  {
    company: 'SalesPad',
    companyUrl: 'https://www.salespad.com/',
    description: [
      'Internship completed during the spring semester through summer break of my junior yea.',
      'Worked on package builder solution that packaged ​n​ sized items into ​k​ sized boxes (related to the Bin packing problem).',
      'Collaborated with developers, managers, and product team to learn about product and development lifecycles and built out small features.',
      'Analyzed performance, maintained, and enhanced the SalesPad application.',
    ],
    endDate: {
      displayDate: 'Aug 2015',
      valueDate: '2015-08',
    },
    jobTitle: 'Junior C# Developer',
    startDate: {
      displayDate: 'Mar 2015',
      valueDate: '2015-05',
    },
    svgComponent: S,
    svgPrimaryColor: '#E04429',
    svgSecondaryColor: '#C4351C',
    technologies: ['C#', 'Git', 'Jira', 'Agile'],
  },
  {
    company: 'Calvin University',
    companyUrl: 'https://calvin.edu/',
    description: [
      'Graduated in 2016 with a Bachelor of Science (B.S.), Computer Science.',
      'Completed courses like Computer Security, Data Structures and Algorithms, High Performance Computing, Operating Systems and Networking, Programming Language Concepts, Software Engineering, Website Administration, and Agile Game Development in South Korea',
    ],
    endDate: {
      displayDate: 'June 2016',
      valueDate: '2016-06',
    },
    jobTitle: 'CS Undergrad Student',
    startDate: {
      displayDate: 'Sep 2013',
      valueDate: '2013-09',
    },
    svgComponent: C,
    svgPrimaryColor: '#D0394F',
    svgSecondaryColor: '#B62B40',
    technologies: [
      'JavaScript',
      'CSS',
      'HTML',
      'C#',
      'C++',
      'C',
      'Java',
      'Python',
      'LISP',
      'Ruby',
      'MeteorJS',
      'AngularJS',
      'Objective-C',
      'Drupal',
      'Assembly',
      'Unity',
      'Git',
    ],
  },
];

export default WORK_EXPERIENCE;
